# Generated by Django 5.2.5 on 2025-08-26 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ativos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipamento',
            name='categoria',
            field=models.CharField(choices=[('Perifericos', 'Periféricos'), ('Maquinas', 'Máquinas'), ('Monitores', 'Monitores')], default='Maquinas', max_length=20),
        ),
    ]
